Tell Spark to overwrite JAR files when running the Spark interface
Summary:
I was seeing errors like:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 4 times, most recent failure: Lost task 0.3 in stage 4.0 (TID 69, 172.17.0.60): org.apache.spark.SparkException: File ./SPe75b8e007ac647a28a729280e4f2769f exists and does not match contents of http://172.17.0.60:9000/api/v1/pipelines/SPe75b8e007ac647a28a729280e4f2769f
```

When I was updating JAR files in the interface. I'm pretty sure this is because if the executor is still running, Spark by default will refuse to overwrite old dependencies with the same name. This should ensure that this overwriting does indeed happen.

Test Plan: manual

Reviewers: hurshal, ankur, joseph, carl

Reviewed By: carl

Subscribers: engineering-list

Differential Revision: http://grizzly.memsql.com/D12062