Fixed NoSuchMethodException error
Summary:
In Databricks our connector is throwing
```
NoSuchMethodException: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(Lscala/PartialFunction;)Lorg/apache/spark/sql/catalyst/plans/logical/LogicalPlan; at
```
error.
Looks like Spark version which is used there differs from the oficial Spark release.
transform is equivalent for transformDown in our case and it works well in Databricks
**Design doc/spec**:
**Docs impact**: none

Test Plan:
Manually tested on Databricks
https://webapp.io/memsql/commits?query=repo%3Asinglestore-spark-connector+id%3A98

Reviewers: pmishchenko-ua

Reviewed By: pmishchenko-ua

Subscribers: engineering-list

JIRA Issues: PLAT-5990

Differential Revision: https://grizzly.internal.memcompute.com/D53802