use same default for json columns as we use for text and blob columns
Summary:
this is a bug uncovered in support:
```
val r = sqlContext.sparkContext.parallelize(Seq(Row(Array("abc"))))
val s = StructType(Seq(StructField("test", JsonType, false)))
val newdf = sqlContext.createDataFrame(r, s)
newdf.write.format("com.memsql.spark.connector").save("test_db.test_table")

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB/TEXT column 'test' can't have a default value
```

the `JsonType` column is erroneously emitting this SQL:
```
CREATE TABLE IF NOT EXISTS `db`.`test` (`test` json NOT NULL DEFAULT '0'...
```
instead of
```
CREATE TABLE IF NOT EXISTS `db`.`test` (`test` json NOT NULL DEFAULT ''...
```

Test Plan:
manual
sbt test

Reviewers: carl, wsong, allan, john

Subscribers: engineering-list

Differential Revision: https://grizzly.memsql.com/D15059